# Generated by Django 5.2.8 on 2025-11-27 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=70)),
                ('telefone', models.CharField(max_length=20, unique=True)),
                ('moto', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('problema_relatado', models.TextField(max_length=500)),
                ('servico_executado', models.TextField(max_length=500)),
                ('mecanico_responsavel', models.CharField(max_length=30)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('atendente_responsavel', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
