# Generated by Django 5.2.8 on 2025-12-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='placa',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
